language: python
python:
    - "3.5"
install:
    - "pip install -r requirements.txt"
before_script:
    - createdb -U postgres open511
    - psql -U postgres -d open511 -c "CREATE EXTENSION postgis"
script:
    - python tests.py