language: python
python:
    - "3.5"
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pip-cache
install:
    - "pip install open511 python-dateutil psycopg2"
before_script:
    - createdb -U postgres open511
    - psql -U postgres -d open511 -c "CREATE EXTENSION postgis"
script:
    - python geotrafic511/tests.py